pywebapp/calendar/forms.py
from datetime import time

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError, DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired

from wtforms_components import TimeField, DateRange

from ..models import Customer, DatesTable, TimeTable, CalendarTable, Employee, Room


class NewDateForm(FlaskForm):
    """
    Form fo new Date creation
    """
    # Customer
    customer_id = QuerySelectField('Kunde', query_factory=lambda: Customer.query.all(),
                                  get_label='id')
    customer_first_name = StringField('Vorname', validators=[DataRequired()])
    customer_last_name = StringField('Nachname', validators=[DataRequired()])
    # Employee
    employee_id = QuerySelectField('Mitarbeiternummer', query_factory=lambda: Employee.query.all(),
                                  get_label='id')
    employee = QuerySelectField('Tätowierer/in', query_factory=lambda: Employee.query.all(),
                                   get_label='full_name')
    # Date Planning
    date = DateField('Datum', validators=[DataRequired()], format="%d.%m.%Y")
    start_time = QuerySelectField('Startzeit', query_factory=lambda: TimeTable.query.all(),
                                  get_label='full_time')
    room_id = QuerySelectField('Raum', query_factory=lambda: Room.query.all(),
                                  get_label='id')
    duration = StringField('Geplante Länge (in Minuten)', validators=[DataRequired()])
    submit = SubmitField('Termin anlegen')

pywebapp/calendar/__init__.py
from flask import Blueprint

calendar = Blueprint('calendar', __name__)

from . import views

pywebapp/calendar/views.py
from datetime import datetime

from flask import flash, redirect, render_template, url_for
from flask_login import login_required

from . import calendar
from .forms import NewDateForm
from .. import db
from ..globals import title_name
from ..models import DatesTable, Employee, Customer


@calendar.route('/dates')
@login_required
def dates():
    """
    Render the contact template on the /felicia route
    """
    Title = "Kalendar"

    return render_template('secured/calendar/date.html', title=str(title_name + ' - ' + Title))


@calendar.route('/dates/add', methods=['GET', 'POST'])
@login_required
def add_date():
    """
    Add a new date into the database.
    """

    Title = "Termin erstellen"
    add_date = True

    form = NewDateForm()
    if form.validate_on_submit():
        new_date_plan = DatesTable(
            date=form.date.data,
            customer_id=form.customer_id.data,
            customer=str(form.customer_first_name.data) + " " + str(form.customer_last_name.data),
            employee_id=form.employee_id.data,
            employee=form.employee.data,
            room=form.room_id.data,
            start_time=form.start_time.data,
            duration=form.duration.data

        )

        db.session.add(new_date_plan)
        db.session.commit()

        return redirect(url_for('dates.calendar'))
    else:

        flash('Termin ungültig! Bitte wähle ein aderes Datum oder einen anderen Zeitrahmen!')

    return render_template('secured/calendar/dates.html', title=str(title_name + ' - ' + Title), action="Edit",
                           add_date=add_date, form=form)


@calendar.route('/dates/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_date(id):
    """
    Edit date informations within the database
    """

    Title = "Termin erstellen"
    add_date = False

    _date = DatesTable.query.get_or_404(id)

    form = NewDateForm(obj=_date)
    if form.validate_on_submit():
            _date.id = form.date_id.data,
            _date.customer_id = form.customer_id.data,
            _date.customer = str(form.customer_first_name.data) + " " + str(form.customer_last_name.data),
            _date.employee_id = form.employee_id.data,
            _date.employee = form.employee.data,
            _date.room = form.room_id.data,
            _date.start_time = form.start_time.data,
            _date.duration = form.duration.data
            db.session.commit()

            flash("Termin erfolgreich bearbeitet!")

            return redirect(url_for('dates.dates'))

    form.date_id.data = _date.id
    form.customer_id.data = _date.customer_id
    form.customer.data = _date.customer
    form.employee_id.data = _date.employee_id
    form.employee.data = _date.employee
    form.room_id.data = _date.room
    form.start_time.data = _date.start_time
    form.duration.data = _date.duration

    return render_template('secured/calendar/dates.html', title=str(title_name + ' - ' + Title), action="Edit",
                           add_date=add_date, form=form,
                           date=_date)

pywebapp/templates/secured/calendar/date.html
{% extends "base.html" %}

{% block content %}
    <style>
        table, th, td {
            border: 1px solid lightgrey;
            border-collapse: collapse;
        }

        th, td {
            width: 100%;
            padding: 5px;
            text-align: center;
        }
    </style>
    <!-- @ToDo DatePicker ... Default Today-->
    <label for="date_picker">Datum: </label>
    <input id="date_picker" type="date" value="{{ now.strftime('%Y-%m-%d') }}"/>

    <!-- @ToDo Calender Display -->
    <table>
        <thead>
        <tr> <!-- <tr></tr> = ist die Definition einer Zeile in einer Tabelle -->
            <th>Uhrzeit</th> <!-- <th></th> = ist die Definition einer Header(Überschrift)-Zelle -->
            <th>Raum 1</th>
            <th>Raum 2</th>
        </tr>
        </thead>
        <tbody>
        {% if dates == date %}
            {% for tdates in termin_dates %}
                {% for time in time.time_list_id %}
                    {% if tdates.start_time <= tdates.time <= tdates.end_time and tdates.room_id == 1 %}
                        <tr id={{ tdates.time }}>
                            <th scope="row">{{ tdates.time }}</th>
                            <td style="background-color: {{ tdates.employee_color }}"> {{ tdates.room_1 }} </td>
                            <td> {{ tdates.room_2 }} </td>
                        </tr>
                    {% elif tdates.start_time <= tdates.time <= tdates.end_time and tdates.room_id == 2 %}
                        <tr id={{ tdates.time }}>
                            <th scope="row">{{ tdates.time }}</th>
                            <td> {{ tdates.room_1 }} </td>
                            <td style="background-color: {{ tdates.employee_color }}"> {{ tdates.room_2 }} </td>
                        </tr>
                    {% else %}
                        <tr id={{ time.time }}>
                            <th scope="row">{{ time.time }}</th>
                            <td> {{ tdates.room_1 }} </td>
                            <td> {{ tdates.room_2 }} </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
    <br><br>
    <button><a href="{{ url_for('calendar.add_date') }}">Neuer Termin</a></button>
    <input id="refresh" type="button" value="Kalender aktualisieren" onclick="reload()">

{% endblock %}

pywebapp/templates/secured/calendar/dates.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <div class="outer">
            <div class="middle">
                <div class="inner">
                    <div class="center">
                        {% if add_date %}
                            <h3>Termin erstellen</h3>
                        {% else %}
                            <h3>Termin bearbeiten</h3>
                        {% endif %}
                        <br/>
                        {{ wtf.quick_form(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}