pywebapp/employee/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo

from ..models import Employee


class EmployeeForm(FlaskForm):
    """
    Form for new user creation
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Nutzername', validators=[DataRequired()])
    first_name = StringField('Vorname', validators=[DataRequired()])
    last_name = StringField('Nachname', validators=[DataRequired()])
    password = PasswordField('Passwort', validators=[
        DataRequired(),
        EqualTo('confirm_password')
    ])
    confirm_password = PasswordField('Passwort bestätigen')
    role_id = StringField('Mitarbeiter Rolle [1: Mitarbeiter, 2: Teamleiter, 3: Admin]', validators=[DataRequired()])
    submit = SubmitField('Erstellen')

    def validate_email(self, field):
        if Employee.query.filter_by(email=field.data).first():
            raise ValidationError('Email bereits in Benutzung!')

    def validate_username(self, field):
        if Employee.query.filter_by(username=field.data).first():
            raise ValidationError('Nutzername beretis vergeben!')

pywebapp/employee/__init__.py
from flask import Blueprint

employee = Blueprint('employee', __name__)

from . import views

pywebapp/employee/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import employee
from .forms import EmployeeForm
from .. import db
from ..globals import title_name
from ..models import Employee


def check_admin_role():
    if not current_user.role_id >= 3:
        abort(403)


@employee.route('/employees')
@login_required
def list_employees():
    """
    Display all registered employees in a list
    """
    check_admin_role()

    Title = "Mitarbeiterliste"

    employees = Employee.query.all()

    return render_template('secured/employees/employees.html', title=str(title_name + ' - ' + Title),
                           employees=employees)


@employee.route('/employees/add', methods=['GET', 'POST'])
@login_required
def add_employee():
    """
    Add new Employee and the Account to Database
    """
    check_admin_role()

    Title = "Mitarbeiterkonto einrichten"
    add_employee = True

    form = EmployeeForm()

    if form.validate_on_submit():
        _employee = Employee(
            email=form.email.data,
            username=form.username.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            full_name=str(form.first_name.data) + " " + str(form.last_name.data),
            password=form.password.data,
            role_id=form.role_id.data
        )

        db.session.add(_employee)
        db.session.commit()

        flash('Der Nutzer wurde erfolgreich angelegt. Das Login ist nun möglich.')

    return render_template('secured/employees/employee.html', title=str(title_name + ' - ' + Title),
                           add_employee=add_employee, form=form)


@employee.route('/employees/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_employee(id):
    """
    Edit a Employee
    """

    Title = "Mitarbeiter bearbeiten"
    add_employee = False

    _employee = Employee.query.get_or_404(id)
    form = EmployeeForm(obj=_employee)
    if form.validate_on_submit():
        _employee.email = form.email.data,
        _employee.username = form.username.data,
        _employee.first_name = form.first_name.data,
        _employee.last_name = form.last_name.data,
        _employee.full_name = str(form.first_name.data) + " " + str(form.last_name.data),
        _employee.phone_number = form.phone_number.data,
        db.session.commit()
        flash('Mitarbeiter erfolgreich bearbeitet!')

        # redirect to the departments page
        return redirect(url_for('employee.list_employees'))

    form.email.data = _employee.email
    form.first_name.data = _employee.first_name
    form.last_name.data = _employee.last_name
    return render_template('secured/employees/employee.html', title=str(title_name + ' - ' + Title), action="Edit",
                           add_employee=add_employee, form=form,
                           employee=_employee)


@employee.route('/employees/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_employee(id):
    """
    Delete a Employee from the database
    """
    Title = "Mitarbeiter löschen"

    _employee = Employee.query.get_or_404(id)
    db.session.delete(_employee)
    db.session.commit()
    flash('Mitarbeiter erfolgreich gelöscht.')

    # redirect to the departments page
    return redirect(url_for('employee.list_employees'))

    return render_template(title=str(title_name + ' - ' + Title))

pywebapp/templates/secured/employees/employee.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <div class="outer">
            <div class="middle">
                <div class="inner">
                    <div class="center">
                        {% if add_employee %}
                            <h3>Mitarbeiter einrichten</h3>
                        {% else %}
                            <h3>Mitarbeiter bearbeiten</h3>
                        {% endif %}
                        <br/>
                        {{ wtf.quick_form(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pywebapp/templates/secured/employees/employees.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

{% block extra_css %}

{% endblock %}

{% block content %}
    <div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Mitarbeiter</h1>
                {% if employees %}
                    <hr class="intro-divider">
                    <div class="center">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th width="10%"> Mitarbeiternummer</th>
                                <th width="30%"> Vorname</th>
                                <th width="30%"> Nachname</th>
                                <th width="30%"> Adresse</th>
                                <th width="15%"> Bearbeiten</th>
                                <th width="15%"> Löschen</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for employee in employees %}
                                <tr>
                                    <td> {{ employee.id }} </td>
                                    <td> {{ employee.first_name }} </td>
                                    <td> {{ employee.last_name }} </td>
                                    <td> {{ employee.email }} </td>
                                    <td>
                                        <a href="{{ url_for('employee.edit_employee', id=employee.id) }}">
                                            <i class="fa fa-pencil"></i> Bearbeiten
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ url_for('employee.delete_employee', id=employee.id) }}">
                                            <i class="fa fa-trash"></i> Löschen
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div style="text-align: center">
                {% else %}
                    <div style="text-align: center">
                    <h3> Es sind noch keine Mitarbeiter erstellt worden. </h3>
                    <hr class="intro-divider">
                {% endif %}
                <a href="{{ url_for('employee.add_employee') }}" class="btn btn-default btn-lg">
                    <i class="fa fa-plus"></i>
                    Neuen Mitarbeiter anlegen
                </a>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}