pywebapp/customer/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email

from ..models import Customer


class CustomerForm(FlaskForm):
    """
    Form for new user creation
    """
    id = StringField('Kundennummer', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    first_name = StringField('Vorname', validators=[DataRequired()])
    last_name = StringField('Nachname', validators=[DataRequired()])
    address = StringField('Adresse', validators=[DataRequired()])
    phone_number = StringField('Telefonnummer', validators=[DataRequired()])
    submit = SubmitField('Erstellen')

    def validate_email(self, field):
        if Customer.query.filter_by(email=field.data).first():
            raise ValidationError('Email bereits in Benutzung!')

    def validate_customer_id(self, field):
        if Customer.query.filter_by(id=field.data).first():
            raise ValidationError('Kundennummer bereits vergeben!')

pywebapp/customer/__init__.py
from flask import Blueprint

customer = Blueprint('customer', __name__)

from . import views

pywebapp/customer/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import customer
from .forms import CustomerForm
from .. import db
from ..globals import title_name
from ..models import Customer


@customer.route('/customers')
@login_required
def list_customers():
    """
    Display all known customers in a list
    """

    Title = "Kundenliste"

    customers = Customer.query.all()

    return render_template('secured/customers/customers.html', title=str(title_name + ' - ' + Title), customers=customers)


@customer.route('/customers/add', methods=['GET', 'POST'])
@login_required
def add_customer():
    """
    Add a new Customer Data to database
    """

    Title = "Neuen Kunden anlegen"
    add_customer = True

    form = CustomerForm()

    if form.validate_on_submit():
        _customer = Customer(
            id=form.id.data,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            full_name=str(form.first_name.data) + " " + str(form.last_name.data),
            address=form.address.data,
            phone_number=form.phone_number.data,
        )
        try:
            db.session.add(_customer)
            db.session.commit()

            flash('Der Kunde wurde erfolgreich angelegt. Das anlegen von Terminen und Rechnungen ist nun möglich.')
        except:
            flash('Error: Kunde bereits in der Datenbank vorhanden!')

        return redirect(url_for('customer.list_customers'))

    return render_template('secured/customers/customer.html', title=str(title_name + ' - ' + Title), action="Add",
                           add_customer=add_customer, form=form)


@customer.route('/customers/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_customer(id):
    """
    Edit a Customer
    """

    Title = "Kunde bearbeiten"
    add_customer = False

    _customer = Customer.query.get_or_404(id)
    form = CustomerForm(obj=_customer)
    if form.validate_on_submit():
        _customer.id = form.id.data,
        _customer.email = form.email.data,
        _customer.first_name = form.first_name.data,
        _customer.last_name = form.last_name.data,
        _customer.full_name = str(form.first_name.data) + " " + str(form.last_name.data),
        _customer.address = form.address.data,
        _customer.phone_number = form.phone_number.data,
        db.session.commit()
        flash('Kunde erfolgreich bearbeitet!')

        # redirect to the departments page
        return redirect(url_for('customer.list_customers'))

    form.id.data = _customer.id
    form.email.data = _customer.email
    form.first_name.data = _customer.first_name
    form.last_name.data = _customer.last_name
    form.address.data = _customer.address
    form.phone_number.data = _customer.phone_number
    return render_template('secured/customers/customer.html', title=str(title_name + ' - ' + Title), action="Edit",
                           add_customer=add_customer, form=form,
                           customer=_customer)


@customer.route('/customers/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_customer(id):
    """
    Delete a Customer from the database
    """
    Title = "Kunde löschen"

    _customer = Customer.query.get_or_404(id)
    db.session.delete(_customer)
    db.session.commit()
    flash('Kunde erfolgreich gelöscht.')

    # redirect to the departments page
    return redirect(url_for('customer.list_customers'))

    return render_template(title=str(title_name + ' - ' + Title))

pywebapp/templates/secured/customers/customer.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html' %}

{% block content %}
    <div class="content-section">
        <div class="outer">
            <div class="middle">
                <div class="inner">
                    <div class="center">
                        {% if add_customer %}
                            <h3>Kunden anlegen</h3>
                        {% else %}
                            <h3>Kunden bearbeiten</h3>
                        {% endif %}
                        <br/>
                        {{ wtf.quick_form(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

pywebapp/templates/secured/customers/customers.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

{% block extra_css %}

{% endblock %}

{% block content %}
    <div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Kunden</h1>
                {% if customers %}
                    <hr class="intro-divider">
                    <div class="center">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th width="10%"> Kundennummer</th>
                                <th width="30%"> Vorname</th>
                                <th width="30%"> Nachname</th>
                                <th width="30%"> Adresse</th>
                                <th width="30%"> Telefonnummer</th>
                                <th width="15%"> Bearbeiten</th>
                                <th width="15%"> Löschen</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for customer in customers %}
                                <tr>
                                    <td> {{ customer.id }} </td>
                                    <td> {{ customer.first_name }} </td>
                                    <td> {{ customer.last_name }} </td>
                                    <td> {{ customer.address }} </td>
                                    <td> {{ customer.phone_number }} </td>
                                    <td>
                                        <a href="{{ url_for('customer.edit_customer', id=customer.id) }}">
                                            <i class="fa fa-pencil"></i> Bearbeiten
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ url_for('customer.delete_customer', id=customer.id) }}">
                                            <i class="fa fa-trash"></i> Löschen
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div style="text-align: center">
                {% else %}
                    <div style="text-align: center">
                    <h3> Es sind noch keine Kunden erstellt worden. </h3>
                    <hr class="intro-divider">
                {% endif %}
                <a href="{{ url_for('customer.add_customer') }}" class="btn btn-default btn-lg">
                    <i class="fa fa-plus"></i>
                    Neuen Kunden anlegen
                </a>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}